dag_id: L1_lgd_general_store_cirebon
source: logee-data-prod.stg_sheets.store_cirebon
destination: logee-data-prod.L1_lgd_general.store_cirebon
sql: source/sql/dwh/L1/lgd_general/store_cirebon.sql
schedule: @daily
time_partitioning: published_timestamp
