dag_id: L1_lgd_general_tx_pameungpeuk_ngirim
source: logee-data-prod.stg_sheets.tx_bdg_ngirim
destination: logee-data-prod.L1_lgd_general.tx_pameungpeuk_ngirim
sql: source/sql/dwh/L1/lgd_general/tx_pameungpeuk_ngirim.sql
schedule: @daily
time_partitioning: published_timestamp
