dag_id: L1_visibility_dma_logee_companies
source: logee-data-prod.logee_datalake_raw_production.visibility_dma_logee_companies
destination: logee-data-prod.L1_visibility.dma_logee_companies
sql: source/sql/dwh/L1/visibility/dma_logee_companies.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
