dag_id: L1_visibility_dma_logee_delivery_details
source: logee-data-prod.logee_datalake_raw_production.visibility_dma_logee_deliverydetails
destination: logee-data-prod.L1_visibility.dma_logee_delivery_details
sql: source/sql/dwh/L1/visibility/dma_logee_delivery_details.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
