dag_id: L1_visibility_lgd_service_fee_pip
source: logee-data-prod.logee_datalake_raw_production.visibility_lgd_service_fee_pip
destination: logee-data-prod.L1_visibility.lgd_service_fee_pip
sql: source/sql/dwh/L1/visibility/lgd_service_fee_pip.sql
schedule: 0 */3 * * *
time_partitioning: published_timestamp