dag_id: L1_visibility_lgd_users
source: logee-data-prod.logee_datalake_raw_production.visibility_lgd_users
destination: logee-data-prod.L1_visibility.lgd_users
sql: source/sql/dwh/L1/visibility/lgd_users.sql
schedule: 0 */3 * * *
time_partitioning: modified_at