dag_id: L1_visibility_lgd_sales
source: logee-data-prod.logee_datalake_raw_production.visibility_lgd_sales
destination: logee-data-prod.L1_visibility.lgd_sales
sql: source/sql/dwh/L1/visibility/lgd_sales.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
