dag_id: L2_visibility_lgd_orders
source: logee-data-prod.L1_visibility.lgd_orders
destination: logee-data-prod.L2_visibility.lgd_orders
sql: source/sql/dwh/L2/visibility/lgd_orders.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
depends_on:
  - dag_id: L1_visibility_lgd_orders
    task_id:
      - move_raw_to_L1

schema:
  description: 
  columns:
    master: []
    inherit:
      - table: L1.visibility.lgd_orders
        full_copy: true
        columns: null
