dag_id: L2_visibility_lgd_sales
source: logee-data-prod.L1_visibility.lgd_sales
destination: logee-data-prod.L2_visibility.lgd_sales
sql: source/sql/dwh/L2/visibility/lgd_sales.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
depends_on:
  - dag_id: L1_visibility_lgd_sales
    task_id:
      - move_raw_to_L1