dag_id: L2_visibility_lgd_voucher
source: logee-data-prod.L1_visibility.lgd_voucher
destination: logee-data-prod.L2_visibility.lgd_voucher
sql: source/sql/dwh/L2/visibility/lgd_voucher.sql
schedule: 0 */3 * * *
time_partitioning: modified_at
depends_on:
  - dag_id: L1_visibility_lgd_voucher
    task_id:
      - move_raw_to_L1